-- DIBANGKITKAN oleh tools/buat_seed.py — jangan diedit tangan.
-- Sumber teks Arab: Tes Lisan BK 2.docx

insert into kitab (nama) values ('Tarkib Umdah');

-- 60 ibarat = 60 potongan tarkib dari bank soal asatidz.
-- Dipakai dua kali: sebagai soal BK 2, dan sebagai bahan
-- ketuk-kata untuk BK 1. Satu korpus, dua tingkat.
insert into ibarat (kitab_id, urutan, teks) values
  ((select id from kitab where nama='Tarkib Umdah'), 1, 'الْمِيَاه عَلَى أَرْبَعَة أَقْسَام'),
  ((select id from kitab where nama='Tarkib Umdah'), 2, 'وَجُلُوْد الْمَيْتَةِ تَطْهُر'),
  ((select id from kitab where nama='Tarkib Umdah'), 3, 'وَالسِّوَاك مُسْتَحَب'),
  ((select id from kitab where nama='Tarkib Umdah'), 4, 'وَفُرُوْض الْوُضُوْء سِتَّة أَشْيَاء'),
  ((select id from kitab where nama='Tarkib Umdah'), 5, 'فَالْمَاء أَفْضَل'),
  ((select id from kitab where nama='Tarkib Umdah'), 6, 'وَالذي يَنْقُض الْوُضُوْء سِتَّة أَشْيَاء'),
  ((select id from kitab where nama='Tarkib Umdah'), 7, 'وَهي اِلْتِقَاءُ الْخِتَانين'),
  ((select id from kitab where nama='Tarkib Umdah'), 8, 'وَأَقَلّ الْحَيْض يَوْم'),
  ((select id from kitab where nama='Tarkib Umdah'), 9, 'وَالْمَرْأَة تُخَالِف الرَّجُل'),
  ((select id from kitab where nama='Tarkib Umdah'), 10, 'وَهي رَكْعَتان'),
  ((select id from kitab where nama='Tarkib Umdah'), 11, 'أَمَّا الْمَوَاشِي فَتَجِب الزَّكَاة'),
  ((select id from kitab where nama='Tarkib Umdah'), 12, 'وَالْخَلِيْطان يُزَكِّيان'),
  ((select id from kitab where nama='Tarkib Umdah'), 13, 'الْمَغْرِب وَقْتُه وَاحِد'),
  ((select id from kitab where nama='Tarkib Umdah'), 14, 'وَالْمَتْرُوْك مِنْ الصَّلَاة ثَلَاثَة أَشْيَاء'),
  ((select id from kitab where nama='Tarkib Umdah'), 15, 'الْأُنْثى أَذَانُها مَكْرُوْه'),
  ((select id from kitab where nama='Tarkib Umdah'), 16, 'سَفَرَتْ هِنْد'),
  ((select id from kitab where nama='Tarkib Umdah'), 17, 'مَسَحَ الْمُسَافِر الْخُفَّ'),
  ((select id from kitab where nama='Tarkib Umdah'), 18, 'نَقَصَ الْإِثْم'),
  ((select id from kitab where nama='Tarkib Umdah'), 19, 'طَلَعَ الْبَدْر'),
  ((select id from kitab where nama='Tarkib Umdah'), 20, 'تَرَكَ الْمُصَنِّف قِسْمًا'),
  ((select id from kitab where nama='Tarkib Umdah'), 21, 'تَطْهُرُ'),
  ((select id from kitab where nama='Tarkib Umdah'), 22, 'تَوَلَّدَ'),
  ((select id from kitab where nama='Tarkib Umdah'), 23, 'يَحْرُمُ'),
  ((select id from kitab where nama='Tarkib Umdah'), 24, 'حَصَلَ شَيْء'),
  ((select id from kitab where nama='Tarkib Umdah'), 25, 'وَيُسَنُّ أَنْ يَنْوِي'),
  ((select id from kitab where nama='Tarkib Umdah'), 26, 'يَنْقِي بِهِنَّ الْمَحَلّ'),
  ((select id from kitab where nama='Tarkib Umdah'), 27, 'وَيَجْتَنِبُ اسْتِقْبَال الْقِبْلَة'),
  ((select id from kitab where nama='Tarkib Umdah'), 28, 'يَنْقُضُ الْوُضُوء'),
  ((select id from kitab where nama='Tarkib Umdah'), 29, 'الَّذِي يُوجِبُ الْغُسْل'),
  ((select id from kitab where nama='Tarkib Umdah'), 30, 'خَالَطَهُ جِصّ'),
  ((select id from kitab where nama='Tarkib Umdah'), 31, 'أَنْ يَكُوْنا سَاتِرين'),
  ((select id from kitab where nama='Tarkib Umdah'), 32, 'إِنَّه يَطْهُر بِرَشّ الْمَاء'),
  ((select id from kitab where nama='Tarkib Umdah'), 33, 'صَارَ ظِلّ كُلّ شَيْء مِثْله'),
  ((select id from kitab where nama='Tarkib Umdah'), 34, 'أَنْ يَكُوْن سَفَره فِيْ غَيْر مَعْصِيَة'),
  ((select id from kitab where nama='Tarkib Umdah'), 35, 'إِنَّا نَسْتَغْفِرك'),
  ((select id from kitab where nama='Tarkib Umdah'), 36, 'لَيْسَ الْخَمْر مَاْلا'),
  ((select id from kitab where nama='Tarkib Umdah'), 37, 'مَا دَامَ عَقْله ثَابِتا'),
  ((select id from kitab where nama='Tarkib Umdah'), 38, 'لَكِنَّ النَّوَوِي اِسْتَدْرَكَ عَلَيْه'),
  ((select id from kitab where nama='Tarkib Umdah'), 39, 'كَانَ الْقَاتِل صَبِيّا'),
  ((select id from kitab where nama='Tarkib Umdah'), 40, 'ظَنَنْتُ الْعِيْدين وَاجِبين'),
  ((select id from kitab where nama='Tarkib Umdah'), 41, 'جَعَلْتُ الْخَمْر خُلا'),
  ((select id from kitab where nama='Tarkib Umdah'), 42, 'عَلِمْتُ الْحَج وَاجِبا'),
  ((select id from kitab where nama='Tarkib Umdah'), 43, 'كَأَنَّ الثَّانِي حَرَامٌ'),
  ((select id from kitab where nama='Tarkib Umdah'), 44, 'لَاتَزَال الصَّلَاةُ وَاجِبا'),
  ((select id from kitab where nama='Tarkib Umdah'), 45, 'وَأَنْ يَكُوْن الْعَدَد أَرْبَعين'),
  ((select id from kitab where nama='Tarkib Umdah'), 46, 'وَالْخَامِسُ التُّرَابُ الطَّاهِر'),
  ((select id from kitab where nama='Tarkib Umdah'), 47, 'الْيَسِيرُ مِنَ الدَّمِ وَالْقَيْح'),
  ((select id from kitab where nama='Tarkib Umdah'), 48, 'وَالْحَيَوَانُ كُلّهُ طَاهِرٌ'),
  ((select id from kitab where nama='Tarkib Umdah'), 49, 'وَالْمَيْتَةُ كُلّهَا نَجِسَةٌ'),
  ((select id from kitab where nama='Tarkib Umdah'), 50, 'خَالَطَهُ جِصٌّ أَوْ رَمْل'),
  ((select id from kitab where nama='Tarkib Umdah'), 51, 'إِلَّا السَّمَكَ وَالْجَرَاد'),
  ((select id from kitab where nama='Tarkib Umdah'), 52, 'وَيَخْرُجُ مِنَ الْفَرْجِ ثَلَاثَةُ دِمَاءٍ دَم الْحَيْض'),
  ((select id from kitab where nama='Tarkib Umdah'), 53, 'فَالْحَيْضُ هُوَ الدَّم الْخَارِج'),
  ((select id from kitab where nama='Tarkib Umdah'), 54, 'الصَّلَاةُ الْمَفْرُوضَة'),
  ((select id from kitab where nama='Tarkib Umdah'), 55, 'وَلَوْنُهُ أَسْوَدُ مُحْتَدِم'),
  ((select id from kitab where nama='Tarkib Umdah'), 56, 'إِذَا غَابَ الشَّفَقُ الْفَجْر'),
  ((select id from kitab where nama='Tarkib Umdah'), 57, 'وَثَلَاثُ نَوَافِلَ مُؤَكَّدَات'),
  ((select id from kitab where nama='Tarkib Umdah'), 58, 'إِذَا غَابَ الشَّفَقُ نِصْفه'),
  ((select id from kitab where nama='Tarkib Umdah'), 59, 'سَبْعَةَ عَشَرَ رَكْعَةً رَكْعَتَا الْفَجْرِ'),
  ((select id from kitab where nama='Tarkib Umdah'), 60, 'وَشَرَائِطُ الصَّلَاةِ خَمْسَةُ أَشْيَاءَ طَهَارَة الْأَعْضَاءِ');

insert into soal (ibarat_id, teks, tipe, tingkat, nomor_bank)
select i.id, i.teks, x.tipe, 'BK2', i.urutan
from ibarat i join (values
  (1, 'ismiyah'),
  (2, 'ismiyah'),
  (3, 'ismiyah'),
  (4, 'ismiyah'),
  (5, 'ismiyah'),
  (6, 'ismiyah'),
  (7, 'ismiyah'),
  (8, 'ismiyah'),
  (9, 'ismiyah'),
  (10, 'ismiyah'),
  (11, 'ismiyah'),
  (12, 'ismiyah'),
  (13, 'ismiyah'),
  (14, 'ismiyah'),
  (15, 'ismiyah'),
  (16, 'filiyah'),
  (17, 'filiyah'),
  (18, 'filiyah'),
  (19, 'filiyah'),
  (20, 'filiyah'),
  (21, 'filiyah'),
  (22, 'filiyah'),
  (23, 'filiyah'),
  (24, 'filiyah'),
  (25, 'filiyah'),
  (26, 'filiyah'),
  (27, 'filiyah'),
  (28, 'filiyah'),
  (29, 'filiyah'),
  (30, 'filiyah'),
  (31, 'nawasikh'),
  (32, 'nawasikh'),
  (33, 'nawasikh'),
  (34, 'nawasikh'),
  (35, 'nawasikh'),
  (36, 'nawasikh'),
  (37, 'nawasikh'),
  (38, 'nawasikh'),
  (39, 'nawasikh'),
  (40, 'nawasikh'),
  (41, 'nawasikh'),
  (42, 'nawasikh'),
  (43, 'nawasikh'),
  (44, 'nawasikh'),
  (45, 'nawasikh'),
  (46, 'tabi'),
  (47, 'tabi'),
  (48, 'tabi'),
  (49, 'tabi'),
  (50, 'tabi'),
  (51, 'tabi'),
  (52, 'tabi'),
  (53, 'tabi'),
  (54, 'tabi'),
  (55, 'tabi'),
  (56, 'tabi'),
  (57, 'tabi'),
  (58, 'tabi'),
  (59, 'tabi'),
  (60, 'tabi')
) as x(n, tipe) on x.n = i.urutan;

insert into langkah (tipe, urutan, pertanyaan, bersyarat, sekali_per_sesi) values
  ('lafad', 1, 'Kalimat apa?', null, false),
  ('lafad', 2, 'Tandanya apa?', null, false),
  ('lafad', 3, 'I''robnya apa?', null, false),
  ('lafad', 4, 'Tanda i''robnya apa?', null, false),
  ('lafad', 5, 'Kenapa pakai tanda itu?', null, false),
  ('lafad', 6, 'Ma''rifat atau nakiroh?', 'isim', false),
  ('lafad', 7, 'Kalau ma''rifat, termasuk yang mana?', 'marifat', false),
  ('lafad', 8, 'Penerapan lafad (ubah ke mufrod / tatsniyah / jamak)!', null, false),
  ('lafad', 9, 'Isim mabni: isim dhomir, maushul, atau isyaroh?', 'mabni', false),
  ('ismiyah', 1, 'Jumlah ismiyah atau fi''liyah?', null, false),
  ('ismiyah', 2, 'Jumlah ismiyah itu apa?', null, true),
  ('ismiyah', 3, 'Mubtada''nya mana?', null, false),
  ('ismiyah', 4, 'Apa pengertian mubtada''?', null, true),
  ('ismiyah', 5, 'Termasuk mubtada'' apa?', null, false),
  ('ismiyah', 6, 'Khobarnya mana?', null, false),
  ('ismiyah', 7, 'Khobar itu apa?', null, true),
  ('ismiyah', 8, 'Termasuk khobar apa?', null, false),
  ('ismiyah', 9, 'Tambahlah amil nawasikh! (كان / إنّ / ظنّ)', null, false),
  ('filiyah', 1, 'Jumlah ismiyah atau fi''liyah?', null, false),
  ('filiyah', 2, 'Jumlah fi''liyah itu apa?', null, true),
  ('filiyah', 3, 'Fa''il / naib fa''ilnya mana?', null, false),
  ('filiyah', 4, 'Apa itu fa''il / naib fa''il?', null, false),
  ('filiyah', 5, 'Fa''ilnya dhahir atau dhomir?', null, false),
  ('filiyah', 6, 'Fi''il mabni ma''lum / majhulnya mana?', null, false),
  ('filiyah', 7, 'Kenapa mabni ma''lum / majhul?', null, false),
  ('filiyah', 8, 'Ubahlah ke ma''lum / majhul!', null, false),
  ('nawasikh', 1, 'Ada amil nawasikh atau tidak?', null, false),
  ('nawasikh', 2, 'Mana amil nawasikhnya?', null, false),
  ('nawasikh', 3, 'Amalnya apa?', null, false),
  ('nawasikh', 4, 'Mana isimnya?', null, false),
  ('nawasikh', 5, 'Mana khobarnya?', null, false),
  ('nawasikh', 6, 'Gantilah dengan amil nawasikh lain!', null, false),
  ('nawasikh', 7, 'Buang amil nawasikhnya!', null, false),
  ('tabi', 1, 'Ada tabi'' atau tidak?', null, false),
  ('tabi', 2, 'Yang mana tabi''nya?', null, false),
  ('tabi', 3, 'Termasuk tabi'' yang apa?', null, false),
  ('tabi', 4, 'Apa pengertiannya?', null, false),
  ('tabi', 5, 'Termasuk macam yang mana?', 'selain_athaf', false),
  ('tabi', 6, 'I''robnya apa?', null, false),
  ('tabi', 7, 'Kenapa?', null, false),
  ('tabi', 8, 'Matbu''nya mana?', null, false);

insert into santri (nama) values
  ('Satria'),
  ('Reyhan'),
  ('Nashir'),
  ('Faaiq'),
  ('Ach. Muzaki'),
  ('Abu Reihan'),
  ('Chusnillah'),
  ('Fahmi I'),
  ('Fahmi A.'),
  ('Raihan Muzakki'),
  ('Jadid'),
  ('Adam'),
  ('Rafi'),
  ('Afandi'),
  ('Zada'),
  ('Agil'),
  ('Hilmi'),
  ('Athoillah'),
  ('Ubaid'),
  ('Rubahul Faiz');

insert into ustadz (nama) values
  ('Ust. Ghofar'),
  ('Ust. Farizqi'),
  ('Ust. Rafli'),
  ('Ust. Akmal');

insert into kelompok (nama, urutan) values
  ('Kelompok 1', 1),
  ('Kelompok 2', 2),
  ('Kelompok 3', 3),
  ('Kelompok 4', 4);

insert into kelompok_santri (kelompok_id, santri_id)
select k.id, s.id from (values
  ('Kelompok 1', 'Satria'),
  ('Kelompok 1', 'Reyhan'),
  ('Kelompok 1', 'Nashir'),
  ('Kelompok 1', 'Faaiq'),
  ('Kelompok 1', 'Ach. Muzaki'),
  ('Kelompok 2', 'Abu Reihan'),
  ('Kelompok 2', 'Chusnillah'),
  ('Kelompok 2', 'Fahmi I'),
  ('Kelompok 2', 'Fahmi A.'),
  ('Kelompok 2', 'Raihan Muzakki'),
  ('Kelompok 3', 'Jadid'),
  ('Kelompok 3', 'Adam'),
  ('Kelompok 3', 'Rafi'),
  ('Kelompok 3', 'Afandi'),
  ('Kelompok 3', 'Zada'),
  ('Kelompok 4', 'Agil'),
  ('Kelompok 4', 'Hilmi'),
  ('Kelompok 4', 'Athoillah'),
  ('Kelompok 4', 'Ubaid'),
  ('Kelompok 4', 'Rubahul Faiz')
) as x(kelompok, santri)
join kelompok k on k.nama = x.kelompok
join santri   s on s.nama = x.santri;

