-- Absensi Ma'had Aly 2026 -- 124 mahasantri yang sisanya.
--
-- Semester diambil dari header tiap sheet di file absensi:
--   "SEMESTER I TAHUN AJARAN 2026/2027"     -> 1
--   "SEMESTER III A/B TAHUN AJARAN 2026/2027" -> 3
--   "SEMESTER V TAHUN AJARAN 2026/2027"      -> 5
--   "SEMESTER VII ... GANJIL"                -> 7
--   "SEMESTER VIII ... GENAP"                -> 8
--
-- A dan B pada semester III adalah dua ANGKATAN yang kebetulan sama-sama
-- di semester 3, bukan dua kelas dari satu angkatan. Bedanya tidak
-- disimpan: tidak ada kolom untuk itu, dan merepresentasikan yang belum
-- tentu benar lebih buruk daripada menyimpan semester saja.
--
-- `tahun_masuk` sengaja NULL: NIM memuat tahun, tapi itu hasil baca,
-- bukan data yang tertulis di dokumen.
--
-- `where not exists` sebagai penghalang: aman dijalankan ulang tanpa
-- menggandakan. lower(nama) supaya beda kapital tidak menghasilkan
-- duplikat yang hampir identik.


insert into public.santri (nama, tingkat, semester)
select v.nama, 'BK1', v.semester
from (values
  ('A. Bissri Fanani', 8),
  ('A. Ghofar Wijayanto', 8),
  ('Abdul Adhim Al Fahri', 3),
  ('Achmad Fazabi A. H.', 8),
  ('Achmad Firdaus', 8),
  ('Achmad Ircham Faiz', 8),
  ('Achmad Ubayu Anandyoga', 5),
  ('Achmad Umar', 3),
  ('Adhar Muzakki', 3),
  ('Aditya Kurniawan Saleh', 8),
  ('Affan Farid Al Hadi Putra', 3),
  ('Afifan', 1),
  ('Agus Setiya Budi', 8),
  ('Ah. Firman Ghani Maulana', 7),
  ('Ahmad Danil Hidayat', 8),
  ('Ahmad Fadli Rozaqi', 3),
  ('Ahmad Hafizh Rifqi', 7),
  ('Ahmad Hasan Al Badar', 5),
  ('Ahmad Hasani', 3),
  ('Ahmad Mufadilil Rozak', 7),
  ('Ahmad Rifqi Alhalim', 3),
  ('Ahmad Royhan A.', 1),
  ('Ahmad Zaiful Ilham Hidayatulloh', 7),
  ('Ahmad Zainuri', 3),
  ('Akmal Aqil Wahyu Indrawan', 8),
  ('Alamsyah Lazuardy Ahmad', 3),
  ('Alfis Syahri Nur Huda', 7),
  ('Althaf Ziya Ilhami', 3),
  ('Andika Chandra', 3),
  ('Arif Budianto', 3),
  ('Bagus Cahyo Pratama', 3),
  ('Bayu Aji Kertadinoto', 8),
  ('Dava Setiawan', 3),
  ('Dicky Feryansyah', 8),
  ('Dimas Sabitul Azmi', 3),
  ('Dimas Zaky Ahnaf', 5),
  ('Fadli Iwan Saputra', 3),
  ('Fajar Ramadhan', 3),
  ('Farid Fatahillah H', 5),
  ('Farizqi Adi Guna', 8),
  ('Fikri Ahmad R', 3),
  ('Hafif Fudin Al Munawar', 7),
  ('Hamdan Alif', 1),
  ('Hasan Marzuqi Mu`thi', 5),
  ('Ilham Zayyinul Abidin', 5),
  ('Imam Ahmad Ubaidillah', 8),
  ('Irsyaad Syariifuddin W', 5),
  ('Isya'' Oky', 3),
  ('Jais Holik', 8),
  ('Johan Ahmad Fauzan', 8),
  ('Khubi Anwarul Maulana', 8),
  ('M Afiful Milal', 1),
  ('M Arzaq Al Fatih', 3),
  ('M Farel Tristan', 1),
  ('M Harish A D F', 3),
  ('M Syahrul Fauzi', 3),
  ('M Yazid Irfani', 3),
  ('M. Abror Suriyanto', 8),
  ('M. Ahsani Taqwim', 8),
  ('M. Ahsin Maulana', 8),
  ('M. Alfin Nuril Huda', 3),
  ('M. Asyrof Zain', 7),
  ('M. Faris Anwar', 3),
  ('M. Faza Fauzan Adhima', 5),
  ('M. Firudin', 8),
  ('M. Haqiqi Fadhilah', 5),
  ('M. Ihsan Khoironi', 8),
  ('M. Irsyadul Ibad', 8),
  ('M. Jamil Shobri', 8),
  ('M. Khozin Abdillah', 8),
  ('M. Naufal Najib', 8),
  ('M. Nurjani', 8),
  ('M. Rikza', 8),
  ('M. Salman Al-Farisi', 8),
  ('M. Shobih', 8),
  ('M. Sulthon Auliya', 8),
  ('M. Syukron Ni`am', 7),
  ('M. Ulul Azmi', 3),
  ('M. Vicky Shahrul H.', 8),
  ('M. Wahyu Fahryansyah', 5),
  ('M. Zidanil Rizqi', 1),
  ('Maimun Najib', 3),
  ('Maqdum Alifur Rofiq', 8),
  ('Ma''ruf Awaludin', 8),
  ('Maulana Ilham Firmansyah', 3),
  ('Moch Fatqkhul Adim', 3),
  ('Moch. Husni mubaroq', 3),
  ('Moch. Irfani Fikri maulana', 8),
  ('Moch. Rafli Nazillur Roikhan', 8),
  ('Moh Reyhan', 3),
  ('Mohammad Ibnu Sholeh', 5),
  ('Muhamad Mujayyid Firdaus', 3),
  ('Muhamad Romli Mubarok', 5),
  ('Muhammad Dwi Hilmi Saputra', 3),
  ('Muhammad Fahrul Rossy', 5),
  ('Muhammad Hafizh W', 3),
  ('Musthofa Ahmad', 8),
  ('Najihul Haq A', 8),
  ('Nur Hanafi', 8),
  ('Nurul Ulum', 1),
  ('Putra Pratama Ramadani', 3),
  ('Radjib Hidayatullah', 3),
  ('Ragil Prionggo Jati', 3),
  ('Ramadandy', 1),
  ('Reva Alfa Saputra', 7),
  ('Riki Mahendra Nur Cahyo', 5),
  ('Risky Ahmad Lutfi R', 7),
  ('Risky Ramadhan', 1),
  ('Riyad Jannatil A', 5),
  ('Rizky Firman Ramadhan', 8),
  ('Rizqi Imanda', 3),
  ('Samsul Arifin', 8),
  ('Syukron Zen Sulistio', 5),
  ('Taqi Falsafi', 5),
  ('Trisna Arya Wardana', 3),
  ('Wafa Abrar Muhammad', 3),
  ('Wafiq Salman', 3),
  ('Wildan Sulthonul', 3),
  ('Yahdi Muhsin', 3),
  ('Yoppy Wahyu Ramadhan', 8),
  ('Zadiel Mirbath Albash', 3),
  ('Zamzami Putra Luhur', 5),
  ('Zidan Defkallah', 3),
  ('Zidan Yoga Rosyanto', 3),
) as v(nama, semester)
where not exists (select 1 from public.santri s where lower(s.nama) = lower(v.nama));
